global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 127.0.0.1:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "/etc/alertmanager/am-alerts.yml"

scrape_configs:
- job_name: 'federate'
  honor_labels: true
  metrics_path: '/federate'  
  params:
    'match[]':
      - '{job="node"}'
      - '{__name__=~"job:.*"}'
  static_configs:
  - targets:
    - '10.10.30.1:9090'
    - '10.10.30.2:9090'
    - '10.10.30.4:9090'
    - '10.10.30.5:9090'
    - '10.10.30.6:9090'
    - '10.10.30.7:9090'    
  relabel_configs:
    - source_labels: [__instance__]
      action: keep

