global:
  scrape_timeout: 1m
scrape_configs:
  - job_name: 'node'
    scrape_interval: 1m
    scrape_timeout: 30s
    metrics_path: /metrics
    static_configs:
    - targets:
      - {{default_ip4}}:9100
